name: iamport_flutter
description: Plugin that allows Flutter to use Iamport payment and certification functions.
version: 0.10.18
homepage: https://github.com/iamport/iamport_flutter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  iamport_webview_flutter: ^3.0.7
  json_annotation: ^4.9.0
  uni_links: ^0.5.1
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0
  json_serializable: ^6.8.0
  test: ^1.25.8

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: kr.iamport.iamport_flutter
        pluginClass: IamportFlutterPlugin
      ios:
        pluginClass: IamportFlutterPlugin

  uses-material-design: true

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/iamport-logo.png
